server {
    listen 80;

    # Статика
    location /static/ {
        alias /staticfiles/;
        expires 30d;
        access_log off;
    }

    # Медиа-файлы (если используете)
    location /media/ {
        alias /media/;
        expires 30d;
        access_log off;
    }

    # Все остальные запросы проксируем на Django
    location / {
        proxy_pass http://django_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
