# Generated by Django 5.2 on 2025-05-07 10:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titles_name', models.CharField(max_length=20, unique=True)),
                ('titles_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='IMG/Users')),
                ('played_games', models.BigIntegerField(default=0)),
                ('leader_games', models.BigIntegerField(default=0)),
                ('win_games', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_root', models.BooleanField(default=False)),
                ('is_moder', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Users_and_Titles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Titles', to='registration.titles')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
    ]
