# Generated by Django 5.2 on 2025-07-01 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints_Questions',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('complaint_name', models.CharField(max_length=150)),
                ('complaint_description', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жалоба на вопрос',
                'verbose_name_plural': 'Жалобы на вопросы',
            },
        ),
        migrations.CreateModel(
            name='Complaints_Selections',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('complaint_name', models.CharField(max_length=150)),
                ('complaint_description', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жалоба на подборку',
                'verbose_name_plural': 'Жалобы на Подборки',
            },
        ),
        migrations.CreateModel(
            name='Estimation_Quest_User',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('estimation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('license_name', models.CharField(max_length=50)),
                ('license_description', models.TextField()),
                ('publication', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=150)),
                ('text_question', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(max_length=150)),
                ('answer_description', models.TextField(blank=True, null=True)),
                ('publication', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Selection_Questions',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('publication', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Связь Вопрос Подборка',
                'verbose_name_plural': 'Связи Вопросов и Подборок',
            },
        ),
        migrations.CreateModel(
            name='Selections',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('selection_name', models.CharField(max_length=50)),
                ('private', models.BooleanField(default=False)),
                ('publication', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('publication', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Tags_Questions',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('publication', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Связь Тега с вопросом',
                'verbose_name_plural': 'Связи Тегов с вопросами',
            },
        ),
    ]
