# Generated by Django 5.2 on 2025-07-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints_questions',
            name='complaint_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Complaint_Question_Author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaints_questions',
            name='verified_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Verified_Complaint_Question_Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaints_selections',
            name='complaint_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Complaint_Selection_Author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaints_selections',
            name='verified_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Verified_Complaint_Selection_Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimation_quest_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_Question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenses',
            name='license_adder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='License_Adder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenses',
            name='verified_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Verified_License_Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='license_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='License', to='questions.licenses'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Question_Author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='verified_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Verified_Question_Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimation_quest_user',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Question', to='questions.question'),
        ),
        migrations.AddField(
            model_name='complaints_questions',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Question_Complaint', to='questions.question'),
        ),
        migrations.AddField(
            model_name='selection_questions',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Question_Select', to='questions.question'),
        ),
        migrations.AddField(
            model_name='selection_questions',
            name='verified_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Verified_Selection_Question_Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selections',
            name='selection_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Selection_Author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selections',
            name='verified_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Verified_Selection_Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selection_questions',
            name='selection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Selection', to='questions.selections'),
        ),
        migrations.AddField(
            model_name='complaints_selections',
            name='selections_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Selection_Complaint', to='questions.selections'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tag_Author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='verified_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Verified_Tag_Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags_questions',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Question_Tag', to='questions.question'),
        ),
        migrations.AddField(
            model_name='tags_questions',
            name='tag_adder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tag_Adder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags_questions',
            name='tags_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tag', to='questions.tags'),
        ),
        migrations.AddField(
            model_name='tags_questions',
            name='verified_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Verified_Tag_Question_Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='estimation_quest_user',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='selection_questions',
            unique_together={('selection_id', 'question_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tags_questions',
            unique_together={('tags_id', 'question_id')},
        ),
    ]
