# Generated by Django 5.2 on 2025-05-08 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation_quest_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_Question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimation_quest_user',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='questions.question'),
        ),
        migrations.AlterUniqueTogether(
            name='estimation_quest_user',
            unique_together={('user', 'question')},
        ),
    ]
