# Generated by Django 5.2 on 2025-05-31 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection_questions',
            name='selection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Selection', to='questions.selections'),
        ),
    ]
