# Generated by Django 5.2 on 2025-07-02 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='game_rooms',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
                ('clos_room', models.BooleanField(default=False)),
                ('password_room', models.CharField(blank=True, max_length=50, null=True)),
                ('game_mode', models.IntegerField(choices=[(0, 'Классика'), (1, 'Спорт'), (2, 'Совместный ответ')], default=0)),
                ('room_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)])),
                ('people_on_page', models.JSONField(blank=True, default=dict, null=True)),
                ('room_description', models.TextField(blank=True, null=True)),
                ('early_answer', models.BooleanField(default=True)),
                ('time_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('clear_chat', models.BooleanField(default=False)),
                ('question_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)])),
                ('show_question', models.BooleanField(default=True)),
                ('reading_speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('random_order', models.BooleanField(default=True)),
                ('break_between_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)])),
            ],
            options={
                'verbose_name': 'Игровая комната',
                'verbose_name_plural': 'Игровые комнаты',
            },
        ),
    ]
