# Generated by Django 5.2 on 2025-05-31 08:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0003_alter_selection_questions_selection_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='game_rooms',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
                ('clos_room', models.BooleanField(default=False)),
                ('password_room', models.CharField(max_length=50)),
                ('game_mode', models.IntegerField(choices=[(0, 'Классика'), (1, 'Спорт'), (2, 'Совместный ответ')], default=0)),
                ('room_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)])),
                ('room_description', models.TextField(blank=True, null=True)),
                ('early_answer', models.BooleanField(default=True)),
                ('time_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('clear_chat', models.BooleanField(default=False)),
                ('question_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)])),
                ('show_question', models.BooleanField(default=True)),
                ('reading_speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('random_order', models.BooleanField(default=True)),
                ('break_between_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)])),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captain_game_rooms', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_game_rooms', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader_game_rooms', to=settings.AUTH_USER_MODEL)),
                ('selections', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Selection_Author', to='questions.selections')),
            ],
        ),
    ]
