# Generated by Django 5.2 on 2025-06-02 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game_rooms',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captain_game_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game_rooms',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_game_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game_rooms',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leader_game_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game_rooms',
            name='selections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Selection_Author', to='questions.selections'),
        ),
    ]
