# Generated by Django 5.2 on 2025-06-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_rooms',
            name='previous_captain',
        ),
        migrations.RemoveField(
            model_name='game_rooms',
            name='previous_host',
        ),
        migrations.RemoveField(
            model_name='game_rooms',
            name='previous_leader',
        ),
    ]
