# Generated by Django 5.2 on 2025-06-02 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_rooms',
            options={'verbose_name': 'Игровая комната', 'verbose_name_plural': 'Игровые комнаты'},
        ),
        migrations.AlterField(
            model_name='game_rooms',
            name='password_room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game_rooms',
            name='selections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Selection_Room', to='questions.selections'),
        ),
    ]
