# Generated by Django 5.2 on 2025-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_game_rooms_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_rooms',
            name='people_on_page',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
