# Generated by Django 5.2 on 2025-06-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_game_rooms_people_on_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_rooms',
            name='people_on_page',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
